logging:
  level:
    com:
      liutao: info
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: info
              BasicExtractor: info
    root: info
server:
  port: 88
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    password: 123456
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf8
    username: root
  jackson:
    time-zone: GMT+8
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: false
  thymeleaf:
    cache: true
